"use client";

import { useState } from "react";
import {
  FileText,
  Plus,
  Download,
  Printer,
  Calendar,
  Trophy,
  Users,
  Eye,
  CheckCircle2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { generateTournamentReport, type GenerateReportInput } from "@/actions/reports";
import { formatDate } from "@/lib/utils/format";
import { toast } from "sonner";

interface ReportItem {
  id: string;
  type: string;
  tournament_id: string | null;
  generated_by: string;
  file_url: string;
  parameters: any;
  created_at: string;
  tournaments?: { id: string; name: string; sports?: { name: string } | null } | null;
  users?: { full_name: string; email: string } | null;
}

interface ReportsManagementProps {
  initialReports: ReportItem[];
  tournaments: Array<{ id: string; name: string }>;
}

export function ReportsManagement({ initialReports, tournaments }: ReportsManagementProps) {
  const [reports, setReports] = useState<ReportItem[]>(initialReports);
  const [isGenerateOpen, setIsGenerateOpen] = useState(false);
  const [previewReport, setPreviewReport] = useState<ReportItem | null>(null);
  const [loading, setLoading] = useState(false);

  const [formData, setFormData] = useState<GenerateReportInput>({
    type: "tournament_summary",
    tournament_id: tournaments[0]?.id || "",
  });

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await generateTournamentReport(formData);
      if (!res.success || !res.data) throw new Error(res.error || "Generation failed");

      setReports((prev) => [res.data as any, ...prev]);
      toast.success("Institutional sports report generated!");
      setIsGenerateOpen(false);
    } catch (err: any) {
      toast.error(err.message || "Failed to generate report.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col justify-between gap-4 border-b pb-4 sm:flex-row sm:items-center">
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
            Reports &amp; Sports Audit Center
          </h2>
          <p className="text-sm text-muted-foreground">
            Generate and export institutional NAAC/NBA compliant sports analytics, match histories, and tournament summaries.
          </p>
        </div>

        <Button onClick={() => setIsGenerateOpen(true)} className="gap-2">
          <Plus className="h-4 w-4" />
          <span>Generate New Report</span>
        </Button>
      </div>

      {/* Generated Reports Table */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Archived Institutional Reports</CardTitle>
          <CardDescription>
            Official documents stored and verifiable by sports committee auditors
          </CardDescription>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow className="bg-muted/20">
                <TableHead className="font-bold">Report Category</TableHead>
                <TableHead className="font-bold">Tournament / Scope</TableHead>
                <TableHead className="font-bold">Generated By</TableHead>
                <TableHead className="font-bold">Created Date</TableHead>
                <TableHead className="text-right font-bold">Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {reports.map((r) => (
                <TableRow key={r.id}>
                  <TableCell>
                    <Badge variant="outline" className="text-xs uppercase">
                      {r.type.replace(/_/g, " ")}
                    </Badge>
                  </TableCell>
                  <TableCell className="font-semibold text-foreground">
                    {r.tournaments?.name || r.parameters?.tournament_name || "Campus-Wide"}
                  </TableCell>
                  <TableCell className="text-xs text-muted-foreground">
                    {r.users?.full_name || "Sports Secretary"}
                  </TableCell>
                  <TableCell className="text-xs text-muted-foreground">
                    {formatDate(r.created_at)}
                  </TableCell>
                  <TableCell className="text-right">
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => setPreviewReport(r)}
                      className="h-8 gap-1.5 text-xs text-primary"
                    >
                      <Eye className="h-3.5 w-3.5" />
                      <span>View &amp; Print</span>
                    </Button>
                  </TableCell>
                </TableRow>
              ))}

              {reports.length === 0 && (
                <TableRow>
                  <TableCell colSpan={5} className="py-8 text-center text-sm text-muted-foreground">
                    No reports generated yet. Click &quot;Generate New Report&quot; to compile your first audit report.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Generate Report Dialog */}
      <Dialog open={isGenerateOpen} onOpenChange={setIsGenerateOpen}>
        <DialogContent className="max-w-md">
          <form onSubmit={handleGenerate} className="space-y-4">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-primary" />
                <span>Generate Official Report</span>
              </DialogTitle>
              <DialogDescription>
                Compile automated statistics into an institutional sports documentation summary.
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-3">
              <div>
                <Label htmlFor="type">Report Type</Label>
                <Select
                  value={formData.type}
                  onValueChange={(val: any) => setFormData({ ...formData, type: val })}
                >
                  <SelectTrigger id="type">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="tournament_summary">Tournament Summary &amp; Results</SelectItem>
                    <SelectItem value="player_performance">Student Athlete Performance Audit</SelectItem>
                    <SelectItem value="attendance">Grounds &amp; Facility Attendance</SelectItem>
                    <SelectItem value="financial">Sports Budget &amp; Equipment Logistics</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="tournament">Tournament (Optional)</Label>
                <Select
                  value={formData.tournament_id || ""}
                  onValueChange={(val) => setFormData({ ...formData, tournament_id: val })}
                >
                  <SelectTrigger id="tournament">
                    <SelectValue placeholder="All Tournaments" />
                  </SelectTrigger>
                  <SelectContent>
                    {tournaments.map((t) => (
                      <SelectItem key={t.id} value={t.id}>
                        {t.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                onClick={() => setIsGenerateOpen(false)}
                disabled={loading}
              >
                Cancel
              </Button>
              <Button type="submit" disabled={loading} className="gap-1.5">
                <FileText className="h-4 w-4" />
                <span>{loading ? "Compiling..." : "Generate Report"}</span>
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      {/* Report Preview Modal */}
      <Dialog open={!!previewReport} onOpenChange={(open) => !open && setPreviewReport(null)}>
        <DialogContent className="max-w-3xl p-6">
          <DialogHeader>
            <DialogTitle>Institutional Sports Audit Report</DialogTitle>
          </DialogHeader>

          {previewReport && (
            <div className="space-y-6">
              {/* Printable Paper Frame */}
              <div className="space-y-4 rounded-xl border bg-card p-6 shadow-sm">
                <div className="border-b pb-4 text-center">
                  <h3 className="font-extrabold uppercase tracking-wide text-foreground">
                    K.K. Wagh Institute of Engineering Education &amp; Research
                  </h3>
                  <p className="text-xs uppercase text-muted-foreground">
                    Department of Physical Education &amp; Sports • Internal Quality Audit
                  </p>
                  <Badge variant="outline" className="mt-2 text-[10px]">
                    NAAC Criteria 5.3 Compliant
                  </Badge>
                </div>

                <div className="grid grid-cols-2 gap-4 text-xs">
                  <div>
                    <span className="text-muted-foreground">Report Type:</span>
                    <p className="font-bold uppercase text-foreground">
                      {previewReport.type.replace(/_/g, " ")}
                    </p>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Generated Date:</span>
                    <p className="font-bold text-foreground">
                      {formatDate(previewReport.created_at)}
                    </p>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Scope / Championship:</span>
                    <p className="font-bold text-foreground">
                      {previewReport.tournaments?.name ||
                        previewReport.parameters?.tournament_name ||
                        "Campus-Wide Sports"}
                    </p>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Signatory Officer:</span>
                    <p className="font-bold text-foreground">
                      {previewReport.users?.full_name || "Sports Secretary"}
                    </p>
                  </div>
                </div>

                {/* Key Summary Stats */}
                {previewReport.parameters && (
                  <div className="grid grid-cols-3 gap-3 border-t pt-4 text-center">
                    <div className="rounded-lg bg-muted/40 p-2.5">
                      <span className="text-[10px] text-muted-foreground">Total Squads</span>
                      <p className="font-bold text-foreground">
                        {previewReport.parameters.total_teams || "—"}
                      </p>
                    </div>
                    <div className="rounded-lg bg-muted/40 p-2.5">
                      <span className="text-[10px] text-muted-foreground">Matches Conducted</span>
                      <p className="font-bold text-foreground">
                        {previewReport.parameters.completed_matches ||
                          previewReport.parameters.total_matches ||
                          "—"}
                      </p>
                    </div>
                    <div className="rounded-lg bg-muted/40 p-2.5">
                      <span className="text-[10px] text-muted-foreground">Podium Winner</span>
                      <p className="font-bold text-foreground">
                        {previewReport.parameters.champion || "TBD"}
                      </p>
                    </div>
                  </div>
                )}
              </div>

              <div className="flex justify-end gap-2 print:hidden">
                <Button onClick={() => window.print()} className="gap-2">
                  <Printer className="h-4 w-4" />
                  <span>Print / Save as PDF</span>
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
